#!/bin/bash
# backs up db
if [ $# -eq 1 ];then
	mysqldump -u root -p$1 --all-databases --master-data > backup.sql
	if [ $? != 0 ];then
		rm backup.sql
		echo ***** Error occured *****
	else
	tar -zcvf $(date +'%d-%m-%Y').tar.gz backup.sql
	fi
fi
