#!/bin/bash

if test -f "$1";
then
	echo school file exists
	size=$(cat "$1" | wc -l)
	if [ $size -eq 0 ];
	then
		echo school file is empty
	else
		echo school file is not empty
	fi
else
	echo school file does not exist
fi
